# Generated by Django 4.1 on 2022-08-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_book', models.BooleanField(default=False)),
                ('exam_papers', models.BooleanField(default=False)),
                ('pens', models.BooleanField(default=False)),
                ('rough_sheets', models.BooleanField(default=False)),
                ('stationary', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('eq', 'Enquiry'), ('po', 'Place Order'), ('r', 'Return')], max_length=2),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.materials'),
            preserve_default=False,
        ),
    ]
