# Generated by Django 4.1 on 2022-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_department_materials_alter_order_purpose_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wiki_page',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
