# Generated by Django 4.1 on 2022-08-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.materials'),
        ),
    ]
