# Generated by Django 4.1 on 2022-08-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='exam_papers',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='note_book',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='pens',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='rough_sheets',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='stationary',
        ),
        migrations.AddField(
            model_name='materials',
            name='item',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='materials',
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.ManyToManyField(to='store.materials'),
        ),
    ]
